export const vehicles = [
  {
    id: "TRK001",
    name: "Delivery Truck Alpha",
    licensePlate: "ABC-1234",
    driver: "John Smith",
    status: "driving",
    location: "Victoria Island, Lagos",
    speed: 65,
    lastUpdate: "2 seconds ago",
    fuel: 78,
    battery: 95,
    temperature: 72,
    ignition: true,
    coordinates: { lat: 6.4281, lng: 3.4219 }, // Victoria Island, Lagos
  },
  {
    id: "VAN002",
    name: "Service Van Beta",
    licensePlate: "XYZ-5678",
    driver: "Sarah Johnson",
    status: "stopped",
    location: "Ikeja, Lagos",
    speed: 0,
    lastUpdate: "1 minute ago",
    fuel: 92,
    battery: 88,
    temperature: 68,
    ignition: true,
    coordinates: { lat: 6.6018, lng: 3.3515 }, // Ikeja, Lagos
  },
  {
    id: "TRK003",
    name: "Cargo Truck Gamma",
    licensePlate: "DEF-9012",
    driver: "Mike Wilson",
    status: "offline",
    location: "Apapa Port, Lagos",
    speed: 0,
    lastUpdate: "2 hours ago",
    fuel: 45,
    battery: 12,
    temperature: 65,
    ignition: false,
    coordinates: { lat: 6.4395, lng: 3.3669 }, // Apapa Port, Lagos
  },
  {
    id: "VAN004",
    name: "Express Van Delta",
    licensePlate: "GHI-3456",
    driver: "Emma Davis",
    status: "idling",
    location: "Lekki Phase 1, Lagos",
    speed: 0,
    lastUpdate: "30 seconds ago",
    fuel: 67,
    battery: 91,
    temperature: 70,
    ignition: true,
    coordinates: { lat: 6.4698, lng: 3.5852 }, // Lekki Phase 1, Lagos
  },
]

export const recentEvents = [
  {
    id: 1,
    vehicleId: "TRK001",
    type: "speed_alert",
    message: "Speed limit exceeded (70 mph in 65 mph zone)",
    timestamp: "2 minutes ago",
    severity: "warning",
  },
  {
    id: 2,
    vehicleId: "VAN002",
    type: "stop",
    message: "Vehicle stopped at customer location",
    timestamp: "5 minutes ago",
    severity: "info",
  },
  {
    id: 3,
    vehicleId: "TRK003",
    type: "offline",
    message: "Vehicle went offline",
    timestamp: "2 hours ago",
    severity: "error",
  },
  {
    id: 4,
    vehicleId: "VAN004",
    type: "geofence_entry",
    message: "Entered designated rest area",
    timestamp: "15 minutes ago",
    severity: "info",
  },
]
